build:color.cpp
	g++ -Wall -o color color.cpp `pkg-config --cflags --libs opencv` --std=c++11

calibrate:calibrate.cpp
	g++ -Wall -o calibrate calibrate.cpp `pkg-config --cflags --libs opencv` --std=c++11
clean:
	rm -f color
